=== tonyrog/em2w/src/em2w.dtd
<!ELEMENT Em2w (Site|User)*>
<!ATTLIST Em2w version CDATA #REQUIRED>

<!ELEMENT Site   (Transport*,(Page|User)*)>
<!ATTLIST Site id CDATA #REQUIRED>

<!ELEMENT Transport (Ftp|SFtp|Http)*>

<!ELEMENT Page (User|Item|Content)*>
<!ATTLIST Page id CDATA #REQUIRED>
<!ATTLIST Page charset CDATA "iso-8859-1">

<!ELEMENT Item (User|Content)*>
<!ATTLIST Item id CDATA #REQUIRED>
<!ATTLIST Item subitem-max CDATA "infinite">
<!ATTLIST Item subitem-separtor CDATA  "hr">
<!ATTLIST Item subitem-layout (horizontal|vertical) "vertical">

<!ELEMENT Ftp EMPTY>
<!ATTLIST Ftp host CDATA #REQUIRED>
<!ATTLIST Ftp port CDATA "21">
<!ATTLIST Ftp user CDATA #REQUIRED>
<!ATTLIST Ftp password CDATA #REQUIRED>
<!ATTLIST Ftp path CDATA #IMPLIED>
<!ATTLIST Ftp vpath CDATA #IMPLIED>

<!ELEMENT SFtp EMPTY>
<!ATTLIST SFtp host CDATA #REQUIRED>
<!ATTLIST SFtp port CDATA "22">
<!ATTLIST SFtp user CDATA #REQUIRED>
<!ATTLIST SFtp password CDATA #REQUIRED>
<!ATTLIST SFtp path CDATA #IMPLIED>
<!ATTLIST SFtp vpath CDATA #IMPLIED>

<!ELEMENT Http EMPTY>
<!ATTLIST Http url CDATA #REQUIRED>
<!ATTLIST Http method (put|post) #REQUIRED>
<!ATTLIST Http type (basic|digest) "basic">
<!ATTLIST Http user CDATA #REQUIRED>
<!ATTLIST Http password CDATA #REQUIRED>
<!ATTLIST Http vpath CDATA #IMPLIED>

<!ELEMENT User (Content)*>
<!ATTLIST User id CDATA #REQUIRED>
<!ATTLIST User admin (true|false) #IMPLIED>
<!ATTLIST User verify (require|off|on) "off">

<!ELEMENT Content EMPTY>
<!ATTLIST Content type CDATA #REQUIRED>
<!ATTLIST Content filter (include|exclude) #IMPLIED>

=== tonyrog/em2w/test/config.xml
<?xml version="1.0" encoding = 'ISO-8859-1' ?>
<!DOCTYPE Em2w SYSTEM "em2w.dtd">

<Em2w version="1.0">

  <Site id="demo">
    <Transport>
      <Ftp host="127.0.0.1" 
	user="em2w" password="mail2web" 
	vpath="/em2w"
	path="/home/em2w/upload" />
    </Transport>

    <User id="tony@rogvall.com" admin="true" verify="require">
      <Content type="*/*"/>
    </User>

    <User id="roland.aalto@pixdesign.nu"/>

    <User id="micke@keysendal.com"/>

    <User id="kim@rogvall.com"/>

    <Page id="demo_page1">
      <Content type="text/plain"/>
      <Content type="text/html"/>
      <Content type="image/jpeg"/>
    </Page>
  </Site>

  <Site id="pixcomab.com">
    <Transport>
      <Ftp host="ftp.pixdesign.nu" 
	user="em2w" password="emtowe002" 
	vpath="/em2w"
	path="/em2w_loader" />
    </Transport>

    <User id="roland.aalto@pixdesign.nu"/>
    <User id="kim@rogvall.com"/>
  </Site>    

  <Site id="autosale">
    <Transport>
      <Ftp host="ftp.pixdesign.nu" 
	user="pixdesiger" password="sevenof9" 
	vpath="/autosale"
	path="/pixdesigner/pixel/autosale/em2w" />
    </Transport>

    <User id="roland.aalto@pixdesign.nu"/>
    <User id="kim@rogvall.com"/>
  </Site>    

  <Site id="powerup">
    <Transport>
      <Ftp host="ftp.pixdesign.nu" 
	user="pixdesiger" password="sevenof9" 
	vpath="/powerup/em2w"
	path="/pixdesigner/pixel/powerup/em2w" />
    </Transport>

    <User id="roland.aalto@pixdesign.nu"/>
    <User id="kim@rogvall.com"/>
  </Site>    



  <Site id="test">

    <Transport>
      <Ftp host="ftp.test.nu" 
	user="test" password="test" 
	vpath="/em2w"
	path="/test/em2w" />

      <Http url="http://www.test.nu/em2w" 
	method="put"
	user="test1" password="test1" 
	vpath="/em2w"/>
    </Transport>

    <User id="admin@test.nu">
      <Content type="*/*"/>
    </User>

    <Page id="page1">
      <Item id="i1">
	<Content type="text/html"/>

	<User id="a@foo.com"/>

	<User id="b@bar.com">
	  <Content type="image/jpeg"/>
	</User>
      </Item>

      <Item id="i2">
	<Content type="text/plain"/>
	<User id="a@foo.com"/>
      </Item>

      <Item id="i3">
	<Content type="text/plain"/>
	<User id="b@bar.com"/>
      </Item>

    </Page>

    <Page id="page2">

      <Item id="i21">
	<User id="a@foo.com"/>
      </Item>

      <Item id="i22">
	<User id="a@foo.com"/>
      </Item>

      <Item id="i23">
	<User id="b@bar.com"/>
      </Item>

    </Page>

  </Site>    

</Em2w>
